### ISSUE TITLE
Please make a v0.6 release (Tracking issue for merger of v0.6 into `master` and upload to `crates.io`)

### ISSUE THREAD

**Issue by ctrlcctrlv** [Logicalshift/flo_curves#12]

**Comment by Logicalshift** [comment]
v0.6 has been released. I've made a couple of changes since your last PR:

* `solve_curve_for_t_within` has been renamed to `solve_curve_for_t_along_axis` so its limitations are clear from the name and to make room for a more comprehensive `find_closest_point_on_curve()` or similar function in the future
* The accuracy parameter is no longer optional (as there's a `solve_curve_for_t` function that already omits the parameter)
