### ISSUE TITLE
Stack overflow when calling offset with Beziers that form lines.

### ISSUE THREAD

**Issue by MatthewBlanchard** [Logicalshift/flo_curves#3]
When calling flo_curves::bezier::offset with a compatible bezier with the following control points:

```
[Vector { x: 518.0, y: 765.0 }, Vector { x: 518.0, y: 765.0 }, Vector { x: 163.0, y: 611.0 }, Vector { x: 163.0, y: 611.0 }]
```

The features_for_cubic_bezier function gets stuck in an infinite loop. It seems the line detection on lines 359-364 are at fault unless I'm missing something? All 4 of these points lie along the same line. I'm currently not sure why the code wouldn't detect that, and instead it tries to reverse until the stack overflows.

I'll continue to look into the issue and if I find a solution I'll make a pull request.

**Comment by Logicalshift** [comment]
Ah, yes, I do believe that code is broken: it should only try again once rather than recurse forever. However, I've added a test case with the coordinates that you provided and it's not failing for me. Are those the exact coordinates that produce the error, or are they rounded? I believe floating-point rounding errors can result in this behaviour.

My suspicion would be that there are two 'small' constants involved here: `SMALL_DISTANCE` which is used to determine if points are co-linear or overlap, and `SMALL_DIVISOR` which is used to determine if a canonical curve exists. 'Non-canonical' curves are basically any where the first three control points form a line, but because the transformation between the curve and its canonical form becomes more and more extreme the closer those three points are to being lined up, there's needs to be a cut-off point due to floating-point arithmetic breaking down.

I think an infinite loop happens if:

* We can't find an affine transform for the curve in either direction (to within `SMALL_DIVISOR`)
* w2, w3, w4 are not co-linear to within `SMALL_DISTANCE` in either direction

I think this can happen with values that are very close to one another or which are very large, but not if any of the points overlap precisely.

I think the fix is to stop using `SMALL_DISTANCE` when checking for co-linearity, because if w1, w2 and w3 are co-linear and w4, w3 and w2 are co-linear, then all the points must be co-linear.

**Comment by Logicalshift** [comment]
I've pushed a new version that I think might fix this issue, though I haven't been able to reproduce it in my own tests. The update ensures that `SMALL_DISTANCE` is only used to determine if control points w2 and w3 are overlapping and the shape of the resulting curve.

**Comment by MatthewBlanchard** [comment]
Could this have something to do with the fact I'm implementing my own bezier struct and using your traits? I don't see how that could change anything because the debug print above is from within flo_curves.
