### ISSUE TITLE
Normal calculations degenerate to 0 in the case of lines.

### ISSUE THREAD

**Issue by MatthewBlanchard** [Logicalshift/flo_curves#5]
Feed a line into normal_at_pos in bezier/normal.rs and you'll get back a 0,0 vector. The tangent calculation used there seems to break down in such a case and give you a 0 len tangent. I fixed this with a quick hack to the function, but there's probably a better way to do it:

```rust
  fn normal_at_pos(&self, t: f64) -> Curve::Point {

        // Extract the points that make up this curve
        let w1          = self.start_point();
        let (w2, w3)    = self.control_points();
        let w4          = self.end_point();

        // seems like the math below is degenerate for straight lines returning a tangent vector
        // less than SMALL_DISTANCE so just doing a quick check here and generating our tangent angle
        // differently
        if self.characteristics() == CurveCategory::Linear {
            let point = de_casteljau4(t, w1, w2, w3, w4);
            let tangent = w1 - w4;

            return Curve::Point::from_components(&Curve::Point::to_normal(&point, &tangent));
        }

        // Get the deriviative
        let (d1, d2, d3) = derivative4(w1, w2, w3, w4);

        // Get the tangent and the point at the specified t value
        let point       = de_casteljau4(t, w1, w2, w3, w4);
        let tangent     = de_casteljau3(t, d1, d2, d3);

        // Compute the normal
        let normal      = Curve::Point::to_normal(&point, &tangent);

        Curve::Point::from_components(&normal)
    }
```

**Comment by Logicalshift** [comment]
I've added a few tests for very short lines and I don't see the behaviour you're describing (this definitely seems like a case that's worth adding to the tests though). Do you have an example of a line that exhibits the problem?

```
#[test]
fn normal_for_short_line_is_straight_up() {
    let line    = bezier::Curve::from_points(Coord2(0.0,0.0), (Coord2(0.0000000003, 0.0), Coord2(0.0000000007, 0.0)), Coord2(0.0000000010, 0.0));
    let normal  = line.normal_at_pos(0.5);
    let normal  = normal.to_unit_vector();

    // Normal should be a line facing up
    assert!(normal.x().abs() < 0.01);
    assert!(normal.y() > 0.01);
}
```

The algorithm is essentially just multiplications and additions, so I think it should work for lines up to the limit of precision of the coordinate representation.

The conversion to the unit vector is needed here because the vector returned is very small for this case. That will be true for small curves as well as lines I think.

The algorithm does rely on the `Coordinate` implementation for precision: the `derivative` and `de_casteljauX` functions all use the coordinate's own arithmetic operations so will be limited by the precision of the internal representation: could that be a factor in the behaviour you're seeing? `Coord2` used here uses an f64, but eventually the line will be short enough that precision is lost, which could produce a '0,0' result: this would happen faster with an f32 or if the line is very far from the origin.

(In the case of 'line far from the origin' causing issues we can subtract the first point from the other points to restore precision in the calculation, as that doesn't affect the normal)

**Comment by MatthewBlanchard** [comment]
I genuinely hope I'm not sending you on another wild goose chase because of my trait implementation. Here's a bit of additional information:

![Capture](https://user-images.githubusercontent.com/310356/107147557-b749cd00-691c-11eb-8742-060fd301b3d1.PNG)

This creates outputs that look like this:

![Capture](https://user-images.githubusercontent.com/310356/107147609-f710b480-691c-11eb-89d7-32837a4998c9.PNG)

(Some of these artifacts are due to bugs in my code, the lines are what I'm trying to showcase here.

The part of the code that seems to degenerate is derivative4. Two of it's outputs are 0,0 vectors. The bezier control points look good to me and by the time derivative4 gets called I don't think my trait implementation is even involved?

If it's a mistake on my end I sincerely apologize for wasting your time.

**Comment by MatthewBlanchard** [comment]
I'm double checking all my trait implementation stuff now.  I am just not sure how/why a bug like this would manifest only in this particular situation. If Mul<f64> or Add<Coordinate> were broken I would think they would manifest more readily on the curved portions as well.

**Comment by Logicalshift** [comment]
Aha, that does tell me something useful, and I'm now able to reproduce the problem. Curves where the control points overlap have an anomaly at that point which gives them infinite curvature, so they have no tangent (this has caused some bugs before, so I feel I should have thought to try it here). This can also happen if you ask for the normal precisely at a cusp.

I've pushed a new version that uses t=f64::EPSILON instead of t=0.0 to avoid triggering this. I think it's mathematically correct, but it is a somewhat surprising result and probably not a useful result when using the normal to perform other calculations. (I've not checked for the overlap yet as this results in only a very small loss of precision when it's not needed)

**Comment by MatthewBlanchard** [comment]
Results look good, thank you for all your help!
![Capture](https://user-images.githubusercontent.com/310356/107172446-61643c00-6993-11eb-8bac-d23d5a47b798.PNG)

This fix actually creates better results than my hacky one did!
