### ISSUE TITLE
Old version number

### ISSUE THREAD

**Issue by AaronErhardt** [Logicalshift/flo_curves#9]
The README and the docs still tell users to use version 0.4 although 0.5.1 is already out.

Unless you plan to update these lines regularly, it's probably better to not mention the version at all so people simply use the latest version from crates.io.

**Comment by Logicalshift** [comment]
I think having the version number in the README file makes some sense as it's useful if someone finds the crate via something like github instead of crates.io. Having in the docs does seem pointless though as it'll be added by the documentation tool itself, so I've removed it there.

To fix the problem with the README I've updated the version number and added a test that will fail if there's a discrepancy - as there's also sample code in there this seems like something that can be built on to test that as well (something similar to how cargo test already tests the samples in doc comments).

**Comment by AaronErhardt** [comment]
Perfect :+1:
